#pragma once

#include <utility>

#include "quants_date/math/binary_search.h"
#include "quants_date/mpl/the_number_of_days_data.h"

namespace qd { namespace unary { namespace detail {
    struct the_sum_of_days_data {
    public:
        static std::size_t value(const std::size_t y, const std::size_t m);
        static std::pair<std::size_t, std::size_t> find(
            const std::size_t serial_value);
    };

    std::size_t the_sum_of_days_data::value(
        const std::size_t y,
        const std::size_t m)
    {
        static std::size_t const* d[] = {
            mpl::the_sum_of_days_data<1900>::data,
            mpl::the_sum_of_days_data<1901>::data,
            mpl::the_sum_of_days_data<1902>::data,
            mpl::the_sum_of_days_data<1903>::data,
            mpl::the_sum_of_days_data<1904>::data,
            mpl::the_sum_of_days_data<1905>::data,
            mpl::the_sum_of_days_data<1906>::data,
            mpl::the_sum_of_days_data<1907>::data,
            mpl::the_sum_of_days_data<1908>::data,
            mpl::the_sum_of_days_data<1909>::data,
            mpl::the_sum_of_days_data<1910>::data,
            mpl::the_sum_of_days_data<1911>::data,
            mpl::the_sum_of_days_data<1912>::data,
            mpl::the_sum_of_days_data<1913>::data,
            mpl::the_sum_of_days_data<1914>::data,
            mpl::the_sum_of_days_data<1915>::data,
            mpl::the_sum_of_days_data<1916>::data,
            mpl::the_sum_of_days_data<1917>::data,
            mpl::the_sum_of_days_data<1918>::data,
            mpl::the_sum_of_days_data<1919>::data,
            mpl::the_sum_of_days_data<1920>::data,
            mpl::the_sum_of_days_data<1921>::data,
            mpl::the_sum_of_days_data<1922>::data,
            mpl::the_sum_of_days_data<1923>::data,
            mpl::the_sum_of_days_data<1924>::data,
            mpl::the_sum_of_days_data<1925>::data,
            mpl::the_sum_of_days_data<1926>::data,
            mpl::the_sum_of_days_data<1927>::data,
            mpl::the_sum_of_days_data<1928>::data,
            mpl::the_sum_of_days_data<1929>::data,
            mpl::the_sum_of_days_data<1930>::data,
            mpl::the_sum_of_days_data<1931>::data,
            mpl::the_sum_of_days_data<1932>::data,
            mpl::the_sum_of_days_data<1933>::data,
            mpl::the_sum_of_days_data<1934>::data,
            mpl::the_sum_of_days_data<1935>::data,
            mpl::the_sum_of_days_data<1936>::data,
            mpl::the_sum_of_days_data<1937>::data,
            mpl::the_sum_of_days_data<1938>::data,
            mpl::the_sum_of_days_data<1939>::data,
            mpl::the_sum_of_days_data<1940>::data,
            mpl::the_sum_of_days_data<1941>::data,
            mpl::the_sum_of_days_data<1942>::data,
            mpl::the_sum_of_days_data<1943>::data,
            mpl::the_sum_of_days_data<1944>::data,
            mpl::the_sum_of_days_data<1945>::data,
            mpl::the_sum_of_days_data<1946>::data,
            mpl::the_sum_of_days_data<1947>::data,
            mpl::the_sum_of_days_data<1948>::data,
            mpl::the_sum_of_days_data<1949>::data,
            mpl::the_sum_of_days_data<1950>::data,
            mpl::the_sum_of_days_data<1951>::data,
            mpl::the_sum_of_days_data<1952>::data,
            mpl::the_sum_of_days_data<1953>::data,
            mpl::the_sum_of_days_data<1954>::data,
            mpl::the_sum_of_days_data<1955>::data,
            mpl::the_sum_of_days_data<1956>::data,
            mpl::the_sum_of_days_data<1957>::data,
            mpl::the_sum_of_days_data<1958>::data,
            mpl::the_sum_of_days_data<1959>::data,
            mpl::the_sum_of_days_data<1960>::data,
            mpl::the_sum_of_days_data<1961>::data,
            mpl::the_sum_of_days_data<1962>::data,
            mpl::the_sum_of_days_data<1963>::data,
            mpl::the_sum_of_days_data<1964>::data,
            mpl::the_sum_of_days_data<1965>::data,
            mpl::the_sum_of_days_data<1966>::data,
            mpl::the_sum_of_days_data<1967>::data,
            mpl::the_sum_of_days_data<1968>::data,
            mpl::the_sum_of_days_data<1969>::data,
            mpl::the_sum_of_days_data<1970>::data,
            mpl::the_sum_of_days_data<1971>::data,
            mpl::the_sum_of_days_data<1972>::data,
            mpl::the_sum_of_days_data<1973>::data,
            mpl::the_sum_of_days_data<1974>::data,
            mpl::the_sum_of_days_data<1975>::data,
            mpl::the_sum_of_days_data<1976>::data,
            mpl::the_sum_of_days_data<1977>::data,
            mpl::the_sum_of_days_data<1978>::data,
            mpl::the_sum_of_days_data<1979>::data,
            mpl::the_sum_of_days_data<1980>::data,
            mpl::the_sum_of_days_data<1981>::data,
            mpl::the_sum_of_days_data<1982>::data,
            mpl::the_sum_of_days_data<1983>::data,
            mpl::the_sum_of_days_data<1984>::data,
            mpl::the_sum_of_days_data<1985>::data,
            mpl::the_sum_of_days_data<1986>::data,
            mpl::the_sum_of_days_data<1987>::data,
            mpl::the_sum_of_days_data<1988>::data,
            mpl::the_sum_of_days_data<1989>::data,
            mpl::the_sum_of_days_data<1990>::data,
            mpl::the_sum_of_days_data<1991>::data,
            mpl::the_sum_of_days_data<1992>::data,
            mpl::the_sum_of_days_data<1993>::data,
            mpl::the_sum_of_days_data<1994>::data,
            mpl::the_sum_of_days_data<1995>::data,
            mpl::the_sum_of_days_data<1996>::data,
            mpl::the_sum_of_days_data<1997>::data,
            mpl::the_sum_of_days_data<1998>::data,
            mpl::the_sum_of_days_data<1999>::data,
            mpl::the_sum_of_days_data<2000>::data,
            mpl::the_sum_of_days_data<2001>::data,
            mpl::the_sum_of_days_data<2002>::data,
            mpl::the_sum_of_days_data<2003>::data,
            mpl::the_sum_of_days_data<2004>::data,
            mpl::the_sum_of_days_data<2005>::data,
            mpl::the_sum_of_days_data<2006>::data,
            mpl::the_sum_of_days_data<2007>::data,
            mpl::the_sum_of_days_data<2008>::data,
            mpl::the_sum_of_days_data<2009>::data,
            mpl::the_sum_of_days_data<2010>::data,
            mpl::the_sum_of_days_data<2011>::data,
            mpl::the_sum_of_days_data<2012>::data,
            mpl::the_sum_of_days_data<2013>::data,
            mpl::the_sum_of_days_data<2014>::data,
            mpl::the_sum_of_days_data<2015>::data,
            mpl::the_sum_of_days_data<2016>::data,
            mpl::the_sum_of_days_data<2017>::data,
            mpl::the_sum_of_days_data<2018>::data,
            mpl::the_sum_of_days_data<2019>::data,
            mpl::the_sum_of_days_data<2020>::data,
            mpl::the_sum_of_days_data<2021>::data,
            mpl::the_sum_of_days_data<2022>::data,
            mpl::the_sum_of_days_data<2023>::data,
            mpl::the_sum_of_days_data<2024>::data,
            mpl::the_sum_of_days_data<2025>::data,
            mpl::the_sum_of_days_data<2026>::data,
            mpl::the_sum_of_days_data<2027>::data,
            mpl::the_sum_of_days_data<2028>::data,
            mpl::the_sum_of_days_data<2029>::data,
            mpl::the_sum_of_days_data<2030>::data,
            mpl::the_sum_of_days_data<2031>::data,
            mpl::the_sum_of_days_data<2032>::data,
            mpl::the_sum_of_days_data<2033>::data,
            mpl::the_sum_of_days_data<2034>::data,
            mpl::the_sum_of_days_data<2035>::data,
            mpl::the_sum_of_days_data<2036>::data,
            mpl::the_sum_of_days_data<2037>::data,
            mpl::the_sum_of_days_data<2038>::data,
            mpl::the_sum_of_days_data<2039>::data,
            mpl::the_sum_of_days_data<2040>::data,
            mpl::the_sum_of_days_data<2041>::data,
            mpl::the_sum_of_days_data<2042>::data,
            mpl::the_sum_of_days_data<2043>::data,
            mpl::the_sum_of_days_data<2044>::data,
            mpl::the_sum_of_days_data<2045>::data,
            mpl::the_sum_of_days_data<2046>::data,
            mpl::the_sum_of_days_data<2047>::data,
            mpl::the_sum_of_days_data<2048>::data,
            mpl::the_sum_of_days_data<2049>::data,
            mpl::the_sum_of_days_data<2050>::data,
            mpl::the_sum_of_days_data<2051>::data,
            mpl::the_sum_of_days_data<2052>::data,
            mpl::the_sum_of_days_data<2053>::data,
            mpl::the_sum_of_days_data<2054>::data,
            mpl::the_sum_of_days_data<2055>::data,
            mpl::the_sum_of_days_data<2056>::data,
            mpl::the_sum_of_days_data<2057>::data,
            mpl::the_sum_of_days_data<2058>::data,
            mpl::the_sum_of_days_data<2059>::data,
            mpl::the_sum_of_days_data<2060>::data,
            mpl::the_sum_of_days_data<2061>::data,
            mpl::the_sum_of_days_data<2062>::data,
            mpl::the_sum_of_days_data<2063>::data,
            mpl::the_sum_of_days_data<2064>::data,
            mpl::the_sum_of_days_data<2065>::data,
            mpl::the_sum_of_days_data<2066>::data,
            mpl::the_sum_of_days_data<2067>::data,
            mpl::the_sum_of_days_data<2068>::data,
            mpl::the_sum_of_days_data<2069>::data,
            mpl::the_sum_of_days_data<2070>::data,
            mpl::the_sum_of_days_data<2071>::data,
            mpl::the_sum_of_days_data<2072>::data,
            mpl::the_sum_of_days_data<2073>::data,
            mpl::the_sum_of_days_data<2074>::data,
            mpl::the_sum_of_days_data<2075>::data,
            mpl::the_sum_of_days_data<2076>::data,
            mpl::the_sum_of_days_data<2077>::data,
            mpl::the_sum_of_days_data<2078>::data,
            mpl::the_sum_of_days_data<2079>::data,
            mpl::the_sum_of_days_data<2080>::data,
            mpl::the_sum_of_days_data<2081>::data,
            mpl::the_sum_of_days_data<2082>::data,
            mpl::the_sum_of_days_data<2083>::data,
            mpl::the_sum_of_days_data<2084>::data,
            mpl::the_sum_of_days_data<2085>::data,
            mpl::the_sum_of_days_data<2086>::data,
            mpl::the_sum_of_days_data<2087>::data,
            mpl::the_sum_of_days_data<2088>::data,
            mpl::the_sum_of_days_data<2089>::data,
            mpl::the_sum_of_days_data<2090>::data,
            mpl::the_sum_of_days_data<2091>::data,
            mpl::the_sum_of_days_data<2092>::data,
            mpl::the_sum_of_days_data<2093>::data,
            mpl::the_sum_of_days_data<2094>::data,
            mpl::the_sum_of_days_data<2095>::data,
            mpl::the_sum_of_days_data<2096>::data,
            mpl::the_sum_of_days_data<2097>::data,
            mpl::the_sum_of_days_data<2098>::data,
            mpl::the_sum_of_days_data<2099>::data,
            mpl::the_sum_of_days_data<2100>::data,
            mpl::the_sum_of_days_data<2101>::data,
            mpl::the_sum_of_days_data<2102>::data,
            mpl::the_sum_of_days_data<2103>::data,
            mpl::the_sum_of_days_data<2104>::data,
            mpl::the_sum_of_days_data<2105>::data,
            mpl::the_sum_of_days_data<2106>::data,
            mpl::the_sum_of_days_data<2107>::data,
            mpl::the_sum_of_days_data<2108>::data,
            mpl::the_sum_of_days_data<2109>::data,
            mpl::the_sum_of_days_data<2110>::data,
            mpl::the_sum_of_days_data<2111>::data,
            mpl::the_sum_of_days_data<2112>::data,
            mpl::the_sum_of_days_data<2113>::data,
            mpl::the_sum_of_days_data<2114>::data,
            mpl::the_sum_of_days_data<2115>::data,
            mpl::the_sum_of_days_data<2116>::data,
            mpl::the_sum_of_days_data<2117>::data,
            mpl::the_sum_of_days_data<2118>::data,
            mpl::the_sum_of_days_data<2119>::data,
            mpl::the_sum_of_days_data<2120>::data,
            mpl::the_sum_of_days_data<2121>::data,
            mpl::the_sum_of_days_data<2122>::data,
            mpl::the_sum_of_days_data<2123>::data,
            mpl::the_sum_of_days_data<2124>::data,
            mpl::the_sum_of_days_data<2125>::data,
            mpl::the_sum_of_days_data<2126>::data,
            mpl::the_sum_of_days_data<2127>::data,
            mpl::the_sum_of_days_data<2128>::data,
            mpl::the_sum_of_days_data<2129>::data,
            mpl::the_sum_of_days_data<2130>::data,
            mpl::the_sum_of_days_data<2131>::data,
            mpl::the_sum_of_days_data<2132>::data,
            mpl::the_sum_of_days_data<2133>::data,
            mpl::the_sum_of_days_data<2134>::data,
            mpl::the_sum_of_days_data<2135>::data,
            mpl::the_sum_of_days_data<2136>::data,
            mpl::the_sum_of_days_data<2137>::data,
            mpl::the_sum_of_days_data<2138>::data,
            mpl::the_sum_of_days_data<2139>::data,
            mpl::the_sum_of_days_data<2140>::data,
            mpl::the_sum_of_days_data<2141>::data,
            mpl::the_sum_of_days_data<2142>::data,
            mpl::the_sum_of_days_data<2143>::data,
            mpl::the_sum_of_days_data<2144>::data,
            mpl::the_sum_of_days_data<2145>::data,
            mpl::the_sum_of_days_data<2146>::data,
            mpl::the_sum_of_days_data<2147>::data,
            mpl::the_sum_of_days_data<2148>::data,
            mpl::the_sum_of_days_data<2149>::data,
            mpl::the_sum_of_days_data<2150>::data,
            mpl::the_sum_of_days_data<2151>::data,
            mpl::the_sum_of_days_data<2152>::data,
            mpl::the_sum_of_days_data<2153>::data,
            mpl::the_sum_of_days_data<2154>::data,
            mpl::the_sum_of_days_data<2155>::data,
            mpl::the_sum_of_days_data<2156>::data,
            mpl::the_sum_of_days_data<2157>::data,
            mpl::the_sum_of_days_data<2158>::data,
            mpl::the_sum_of_days_data<2159>::data,
            mpl::the_sum_of_days_data<2160>::data,
            mpl::the_sum_of_days_data<2161>::data,
            mpl::the_sum_of_days_data<2162>::data,
            mpl::the_sum_of_days_data<2163>::data,
            mpl::the_sum_of_days_data<2164>::data,
            mpl::the_sum_of_days_data<2165>::data,
            mpl::the_sum_of_days_data<2166>::data,
            mpl::the_sum_of_days_data<2167>::data,
            mpl::the_sum_of_days_data<2168>::data,
            mpl::the_sum_of_days_data<2169>::data,
            mpl::the_sum_of_days_data<2170>::data,
            mpl::the_sum_of_days_data<2171>::data,
            mpl::the_sum_of_days_data<2172>::data,
            mpl::the_sum_of_days_data<2173>::data,
            mpl::the_sum_of_days_data<2174>::data,
            mpl::the_sum_of_days_data<2175>::data,
            mpl::the_sum_of_days_data<2176>::data,
            mpl::the_sum_of_days_data<2177>::data,
            mpl::the_sum_of_days_data<2178>::data,
            mpl::the_sum_of_days_data<2179>::data,
            mpl::the_sum_of_days_data<2180>::data,
            mpl::the_sum_of_days_data<2181>::data,
            mpl::the_sum_of_days_data<2182>::data,
            mpl::the_sum_of_days_data<2183>::data,
            mpl::the_sum_of_days_data<2184>::data,
            mpl::the_sum_of_days_data<2185>::data,
            mpl::the_sum_of_days_data<2186>::data,
            mpl::the_sum_of_days_data<2187>::data,
            mpl::the_sum_of_days_data<2188>::data,
            mpl::the_sum_of_days_data<2189>::data,
            mpl::the_sum_of_days_data<2190>::data,
            mpl::the_sum_of_days_data<2191>::data,
            mpl::the_sum_of_days_data<2192>::data,
            mpl::the_sum_of_days_data<2193>::data,
            mpl::the_sum_of_days_data<2194>::data,
            mpl::the_sum_of_days_data<2195>::data,
            mpl::the_sum_of_days_data<2196>::data,
            mpl::the_sum_of_days_data<2197>::data,
            mpl::the_sum_of_days_data<2198>::data,
            mpl::the_sum_of_days_data<2199>::data
        };

        return d[y - 1900][m - 1];
    }

    inline std::pair<std::size_t, std::size_t>
        the_sum_of_days_data::find(const std::size_t serial_value)
    {
        const auto year
            = math::binary_search(
                serial_value,
                1900u,
                2199u,
                [](const std::size_t y){ return value(y, 1); });
        const auto month
            = math::binary_search(
                serial_value,
                1u,
                12u,
                [year](const std::size_t m){ return value(year, m); });

        return std::make_pair(year, month);
    }

    std::size_t to_serial_value_impl(
        const std::size_t y,
        const std::size_t m,
        const std::size_t d)
    {
        return detail::the_sum_of_days_data::value(y, m) + d;
    }
}}}